//! Build script: emits a compile-time build timestamp and stages optional
//! embedded files (files that may or may not exist in the repo yet) into
//! OUT_DIR so `include_str!` always has something to include.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));

    // Build timestamp (UTC, RFC3339). Computed here, at compile time — the
    // Worker never calls Date::now for this.
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .expect("clock after epoch")
        .as_secs();
    println!("cargo:rustc-env=BUILD_TIMESTAMP={}", rfc3339_utc(secs));

    // predictions/scores.csv is generated by scoring/ and does not exist yet.
    // Copy it into OUT_DIR when present, otherwise stage an empty placeholder,
    // so the crate builds either way and picks the file up once it appears.
    stage_optional(
        Path::new("../predictions/scores.csv"),
        &out_dir.join("scores.csv"),
    );
    println!("cargo:rerun-if-changed=../predictions/scores.csv");
}

fn stage_optional(src: &Path, dst: &Path) {
    if src.exists() {
        fs::copy(src, dst).expect("copy optional embedded file");
    } else {
        fs::write(dst, "").expect("write placeholder for optional embedded file");
    }
}

/// Days-from-epoch to civil date (Howard Hinnant's algorithm), no deps.
fn rfc3339_utc(secs: u64) -> String {
    let days = secs / 86_400;
    let rem = secs % 86_400;
    let (h, m, s) = (rem / 3600, (rem % 3600) / 60, rem % 60);
    let z = days as i64 + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z.rem_euclid(146_097);
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let mo = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if mo <= 2 { y + 1 } else { y };
    format!("{y:04}-{mo:02}-{d:02}T{h:02}:{m:02}:{s:02}Z")
}
